version: '3.3'

x-function: &base_backend
  build:
    context: .
    dockerfile: app.dockerfile
  volumes:
    - poetry-volume:/opt/poetry:delegated
  environment: &env-vars
    POETRY_HOME: /opt/poetry
    DB_HOST: ${DB_HOST}
    DB_NAME: ${DB_NAME}
    DB_USER: ${DB_USER}
    DB_PASS: ${DB_PASSWORD}
  networks:
    - internal
  depends_on:
    - db
  env_file:
    - .env

x-function: &base_celery
  <<: *base_backend
  entrypoint: celery
  volumes:
      - static_dir:/opt/src/static/
      - media_dir:/opt/src/media/
      - ./web:/opt/web:rw
  links:
    - redis
  depends_on:
    - db
    - redis

services:
  db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:14.6-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata:rw
    env_file:
      - .env
    networks:
      - internal
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - static_dir:/opt/web/static/
      - media_dir:/opt/web/media/
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - internal

  web:
    <<: *base_backend
    container_name: ${PROJECT_NAME}_web
    volumes:
      - static_dir:/opt/src/static/
      - media_dir:/opt/src/media/
      - ./web:/opt/web:rw
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn web.core.wsgi:application --bind 0.0.0.0:8000"

  bot:
    <<: *base_backend
    container_name: ${PROJECT_NAME}_bot
    volumes:
      - ./bot:/opt/bot:rw
    command: >
      sh -c "python bot/main.py"

  redis:
    image: redis:7.0.11-alpine
    hostname: redis
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - internal
    env_file:
      - .env

  worker:
    <<: *base_celery
    hostname: worker
    command: >
      -A web.core.celery worker -l info -P gevent

  beat:
    <<: *base_celery
    hostname: beat
    command: >
      -A web.core.celery beat -l debug


volumes:
  static_dir:
  media_dir:
  pg_data:
  redis_data:
  poetry-volume:                 

networks:
  internal: