version: '3.3'

x-function: &base_backend
  build:
    context: .
    dockerfile: app.dockerfile
  volumes:
    - ./:/DoctorBot
    - poetry-volume:/opt/poetry:delegated
  environment: &env-vars
    POETRY_HOME: /opt/poetry
    DB_HOST: ${DB_HOST}
    DB_NAME: ${DB_NAME}
    DB_USER: ${DB_USER}
    DB_PASS: ${DB_PASSWORD}
  networks:
    - internal
  depends_on:
    - app_db
  env_file:
    - .env

x-function: &base_celery
  <<: *base_backend
  entrypoint: celery
  links:
    - redis
  depends_on:
    - app_db
    - redis

services:
  app_db:
    container_name: ${PROJECT_NAME}_db
    image: postgres:11
    volumes:
      - app_db-template:/var/lib/postgresql/data/pgdata:rw
    env_file:
      - .env
    networks:
      - internal
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata

  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    volumes:
    - ./:/DoctorBot
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - internal

  web:
    <<: *base_backend
    container_name: ${PROJECT_NAME}_web
    command: >
      sh -c "python manage.py migrate && gunicorn app.wsgi:application --bind 0.0.0.0:8000"

  bot:
    <<: *base_backend
    container_name: ${PROJECT_NAME}_bot
    command: >
      sh -c "python bot/main.py"

  redis:
    image: redis:7.0.11-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - internal

  worker:
    <<: *base_celery
    hostname: worker
    command: >
      -A web.core.celery worker -l info -P gevent

  beat:
    <<: *base_celery
    hostname: beat
    command: >
      -A web.core.celery beat -l debug


volumes:
  app_db-template:
  poetry-volume:

networks:
  internal:

