# Generated by Django 4.2.1 on 2024-11-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugs', models.JSONField(default=[], verbose_name='Список препаратов')),
                ('patient_name', models.CharField(max_length=150, verbose_name='Имя пациента')),
                ('first_take', models.DateField(verbose_name='День первого приема')),
                ('last_take', models.DateField(verbose_name='День последнего приема')),
                ('time_to_take', models.TimeField(verbose_name='Время приема')),
                ('reception_calendar', models.JSONField(default={}, verbose_name='Календарь према препаратов')),
                ('notifications_calendar', models.JSONField(default={}, verbose_name='Календарь для проверки отправки уведомлений')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='doctors.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
            },
        ),
    ]
