# Generated by Django 4.2.1 on 2024-11-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(db_index=True, max_length=150, verbose_name='Имя пациента')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='doctors.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
            },
        ),
    ]
