# Generated by Django 4.2.1 on 2024-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='drugs',
            field=models.JSONField(default=list, verbose_name='Список препаратов'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='last_take',
            field=models.DateField(db_index=True, verbose_name='День последнего приема'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='notifications_calendar',
            field=models.JSONField(db_index=True, default=dict, verbose_name='Календарь для проверки отправки уведомлений'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='patient_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Имя пациента'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='reception_calendar',
            field=models.JSONField(default=dict, verbose_name='Календарь према препаратов'),
        ),
    ]
