# Generated by Django 4.2.1 on 2024-11-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_alter_protocol_drugs_alter_protocol_last_take_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_take', models.DateField(verbose_name='День первого приема')),
                ('last_take', models.DateField(db_index=True, verbose_name='День последнего приема')),
                ('time_to_take', models.TimeField(verbose_name='Время приема')),
                ('reception_calendar', models.JSONField(default=dict, verbose_name='Календарь према препаратов')),
                ('notifications_calendar', models.JSONField(default=dict, verbose_name='Календарь для проверки отправки уведомлений')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='first_take',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='last_take',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='notifications_calendar',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='reception_calendar',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='time_to_take',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='drugs',
        ),
        migrations.AddField(
            model_name='protocol',
            name='drugs',
            field=models.ManyToManyField(related_name='protocols', to='protocols.drug', verbose_name='Препараты'),
        ),
    ]
