# Generated by Django 4.2.1 on 2024-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
        ('protocols', '0003_drug_remove_protocol_first_take_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.AlterField(
            model_name='protocol',
            name='drugs',
            field=models.ManyToManyField(related_name='protocols', to='drugs.drug', verbose_name='Препараты'),
        ),
    ]
