# Generated by Django 4.2.1 on 2024-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('first_take', models.DateField(verbose_name='День первого приема')),
                ('last_take', models.DateField(db_index=True, verbose_name='День последнего приема')),
                ('time_to_take', models.TimeField(verbose_name='Время приема')),
                ('reception_calendar', models.JSONField(default=dict, verbose_name='Календарь према препаратов')),
                ('notifications_calendar', models.JSONField(default=dict, verbose_name='Календарь для проверки отправки уведомлений')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
    ]
