# Generated by Django 4.2.1 on 2024-11-29 14:54

from django.db import migrations, models
import django.db.models.deletion
import web.utils.db.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.CharField(db_index=True, default=web.utils.db.model_mixins.ulid_default, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('first_take', models.DateField(verbose_name='День первого приема')),
                ('last_take', models.DateField(db_index=True, verbose_name='День последнего приема')),
                ('time_to_take', models.TimeField(verbose_name='Время приема')),
                ('reception_calendar', models.JSONField(default=dict, verbose_name='Календарь према препаратов')),
                ('notifications_calendar', models.JSONField(default=dict, verbose_name='Календарь для проверки отправки уведомлений')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='protocols.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
                'ordering': ['time_to_take'],
            },
        ),
    ]
